project_name: c3-exporter

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh
        
builds:
    -
        id: c3e
        main: ./cmd/c3-exporter
        binary: sbin/c3-exporterd
        env:
            - CGO_ENABLED=0
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        ignore:
            - goarch: 386
            - goos: openbsd
              goarch: arm64
            - goos: windows
              goarch: arm64
        ldflags:
            - -s
            - -w
            - -extldflags "-static"
            - -X github.com/circonus/c3-exporter/internal/release.version={{.Version}}
            - -X github.com/circonus/c3-exporter/internal/release.commit={{.ShortCommit}}
            - -X github.com/circonus/c3-exporter/internal/release.branch={{.Branch}}
            - -X github.com/circonus/c3-exporter/internal/release.buildDate={{.Date}}
            - -X github.com/circonus/c3-exporter/internal/release.buildTag={{.Tag}}
dockers:
    -
        goos: linux
        goarch: amd64
        goarm: ''
        ids: ['c3e']
        image_templates:
            - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
            - "circonus/{{.ProjectName}}:{{.Tag}}"
            - "circonus/{{.ProjectName}}:latest-amd64"
            - "circonus/{{.ProjectName}}:latest"
        skip_push: false
        dockerfile: builds/docker/x86_64/Dockerfile
        build_flag_templates:
            - "--pull"
            - "--label=org.label-schema.schema-version=1.0"
            - "--label=org.label-schema.version={{.Version}}"
            - "--label=org.label-schema.name={{.ProjectName}}"
            - "--label=org.opencontainers.image.created={{.Date}}"
            - "--label=org.opencontainers.image.title={{.ProjectName}}"
            - "--label=org.opencontainers.image.revision={{.FullCommit}}"
            - "--label=org.opencontainers.image.version={{.Version}}"
            - "--platform=linux/amd64"
        extra_files:
            - etc/example-c3-exporter.yaml
    -
        goos: linux
        goarch: arm64
        goarm: ''
        ids: ['c3e']
        image_templates:
            - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
            - "circonus/{{.ProjectName}}:latest-arm64"
        skip_push: false
        dockerfile: builds/docker/arm64/Dockerfile
        build_flag_templates:
            - "--pull"
            - "--label=org.label-schema.schema-version=1.0"
            - "--label=org.label-schema.version={{.Version}}"
            - "--label=org.label-schema.name={{.ProjectName}}"
            - "--label=org.opencontainers.image.created={{.Date}}"
            - "--label=org.opencontainers.image.title={{.ProjectName}}"
            - "--label=org.opencontainers.image.revision={{.FullCommit}}"
            - "--label=org.opencontainers.image.version={{.Version}}"
            - "--platform=linux/arm64"
        extra_files:
            - etc/example-c3-exporter.yaml

docker_manifests:
    - name_template: "circonus/{{.ProjectName}}:latest"
      image_templates:
        - "circonus/{{.ProjectName}}:latest-amd64"
        - "circonus/{{.ProjectName}}:latest-arm64"
        - "circonus/{{.ProjectName}}:latest"
    - name_template: "circonus/{{.ProjectName}}:{{.Tag}}"
      image_templates:
        - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
        - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
        - "circonus/{{.ProjectName}}:{{.Tag}}"

nfpms:
    - vendor: Circonus, Inc.
      homepage: https://circonus.com
      maintainer: Circonus <support@circonus.com>
      description: Circonus C3 Data Exporter
      license: MIT
      file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      replacements:
        darwin: macOS
      formats:
        - deb
        - rpm
      bindir: /opt/circonus/c3
      contents:
        - src: "LICENSE"
          dst: "/opt/circonus/c3/LICENSE"
        - src: "README.md"
          dst: "/opt/circonus/c3/README.md"
        - src: "CHANGELOG.md"
          dst: "/opt/circonus/c3/CHANGELOG.md"
        - src: "service/circonus-c3-exporter.linux.service"
          dst: "/opt/circonus/c3/service/circonus-c3-exporter.service"
        - src: "service/circonus-c3-exporter.linux.init"
          dst: "/opt/circonus/c3/service/circonus-c3-exporter.init"
        - src: "etc/example-c3-exporter.yaml" 
          dst: "/opt/circonus/c3/etc/c3-exporter.yaml"
          type: "config|noreplace"
      overrides:
        deb:
          scripts:
            preinstall: "builds/deb/pre-install.sh"
            postinstall: "builds/deb/post-install.sh"
            preremove: "builds/deb/pre-remove.sh"
            postremove: "builds/deb/post-remove.sh"
        rpm:
          scripts:
            preinstall: "builds/rpm/pre-install.sh"
            postinstall: "builds/rpm/post-install.sh"
            postremove: "builds/rpm/post-remove.sh"

archives:
    -   
        id: default
        name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
        format: tar.gz
        replacements:
          amd64: x86_64
        format_overrides:
          -
            goos: windows
            format: zip
        files:
          - LICENSE
          - README.md
          - CHANGELOG.md
          - etc/example-c3-exporter.yaml
          - service/*

release:
  github:
    owner: circonus
    name: c3-exporter
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: desc
  abbrev: 0
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Dependencies'
      regexp: "^.*build(deps):+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
